config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :tasks, only: %i[index create update show destroy]
    end
  end

  resources :tasks, only: %i[index new create edit update show destroy] do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_tasks, dependent: :destroy
  has_many :tasks, through: :category_tasks
end

app/models/category_task.rb
class CategoryTask < ApplicationRecord
  belongs_to :category
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :category_tasks, dependent: :destroy
  has_many :categories, through: :category_tasks

  belongs_to :user

  validates :title, :description, presence: true

  scope :search, ->(term) {
    joins(:categories).where(
      'title ILIKE :query OR description ILIKE :query', query: "%#{term}%"
    ).or(where('categories.name ILIKE :query', query: "%#{term}%"))
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, dependent: :destroy
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :authenticate_api_user

  private

  def authenticate_api_user
    return render json: { error: 'Authentication Failed' }, status: 500 unless params.fetch(:user, nil)

    user_params = params.require(:user).permit(:email, :password)

    user = User.find_by_email(user_params[:email])

    @user = user if user.valid_password?(user_params[:password])

    return render json: { error: 'Authentication Failed' }, status: 500 unless @user
  end
end

app/controllers/api/v1/tasks_controller.rb
class Api::V1::TasksController < Api::V1::ApplicationController
  before_action :fetch_task, only: %i[show]

  def index
    @tasks = Task.all
  end

  def show; end

  def create
    @task = @user.tasks.new(task_params)

    if @task.save
      render :show
    else
      render json: @task.errors, status: :unprocessable_entity
    end
  end

  private

  def fetch_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = current_user.tasks.new(task_params)
    return redirect_to @task if @task.save

    render :new
  end

  def update
    @task = current_user.tasks.find(params[:id])
    return redirect_to @task, notice: 'Alterado com sucesso' if @task.update(task_params)

    render :edit
  end

  def destroy
    @task = current_user.tasks.find(params[:id])

    redirect_to tasks_path, notice: 'Apagado com sucesso' if @task.destroy
  end

  def search
    @tasks = Task.search(params[:search_term])

    render :index
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h2><%= t('welcome') %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Listinha</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render  "shared/navbar" %>
    <%= render  partial: "shared/notice_alert" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |message| %>
    <p>
      <%= message %>
    </p>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav>
  <% if user_signed_in? %>
    <%= link_to t('.tasks'), tasks_path %>
  <% else %>
    <%= link_to t('.login'), new_user_session_path %>
  <% end %>
</nav>

app/views/shared/_notice_alert.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/tasks/_form.html.erb
<%= render  "shared/errors", object: @task %>

<%= form_with model: @task, data: { turbo: false } do |f| %>
  <p>
    <%= f.label :title, Task.human_attribute_name(:title) %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description, Task.human_attribute_name(:description) %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :category_ids, t('.categories') %>
    <%= f.select :category_ids, Category.all.collect {|t| [t.name, t.id]},{:prompt=>'--------'}, { multiple: true } %>
  </p>
  <p>
    <%= f.submit t('.save') %>
  </p>
<% end %>

app/views/tasks/_task.html.erb
<p>
  <%= task.id %> | 
  <%= task.title %> | 
  <% if action_name == 'index' %>
    <%= task.description.truncate(5) %> | 
  <% elsif action_name == 'show' %>
    <%= task.description %> | 
  <% end %>

  <% if action_name == 'show' %>
    <%= t('.categories') %>:
    <%= task.categories.pluck(:name).to_sentence%>
  <% end %>

  <br>

  <%= link_to t('details'), task %>

  <% if current_user.tasks.include? task %>
   | 
    <%= link_to t('edit'), edit_task_path(task) %> | 
    <%= link_to t('destroy'), task_path(task), data: { 'turbo-method': :delete } %>
  <% end %>
</p>

<hr>

app/views/tasks/edit.html.erb
<h2><%= t('.edit_task') %></h2>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h2><%= t('.tasks') %></h2>
<p>
  <%= link_to t('.new_task'), new_task_path %>
</p>

<div>
  <%= form_with url: search_tasks_path, data: { turbo: :false }, method: :get do |f| %>
    <%= f.label :search_term, t('.search') %>
    <%= f.text_field :search_term%>

    <%= f.submit t('.do_search') %>
  <% end %>
</div>

<div id="tasks">
  <%= render @tasks %>
</div>

app/views/tasks/new.html.erb
<h2><h2><%= t('.new_task') %></h2></h2>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h2><%= t('.task_detail') %></h2>
<h3><%= @task.model_name.human %> #<%= @task.id %></h3>

<p>
  <%= render @task %>
</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>